version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vault
      POSTGRES_DB: vault
    volumes:
      - postgres-data:/var/lib/postgresql/data
  vault:
    image: vault:latest
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_BACKEND_STORAGE: "postgresql"
      VAULT_POSTGRESQL_CONNECTION_URL: "postgresql://vault:vault@postgres:5432/vault?sslmode=disable"
    ports:
      - "8200:8200"
    depends_on:
      - postgres

volumes:
  postgres-data:
